import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <div className='container' >

      <div style={{ display: "flex",justifyContent:"space-around",marginTop:"30px",marginBottom:"30px" }}>

        <div className='card-top'> Request a quote</div>
        <div className='card-top'> Place an Order</div>
        <div className='card-top'> View Existing Order</div>
        <div className='card-top'> Make Payment</div>
        </div>

        <h5 style={{textAlign:"center",textDecoration:"underline"}}>Your Recent Orders</h5>
        <div style={{ display: "flex", flexWrap: "wrap",justifyContent:"center" }}>
          <div className='card border-wrap m30'>
            <div className='flex-3 '>
              <p className='p10'>Digitizing</p>
              <p className='p10 b-top'>12022021</p>
            </div>
            <div className='flex-6 ' >
              <p className='p10'> <strong>Order</strong></p>
              <p className='p10 b-top'>IHYC frostbite burgee</p>
            </div>
          </div>
          <div className='card border-wrap m30'>
            <div className='flex-3 '>
              <p className='p10'>Artowrk</p>
              <p className='p10 b-top'>12022021</p>
            </div>
            <div className='flex-6 ' >
              <p className='p10'> <strong>Quote</strong></p>
              <p className='p10 b-top'>Texas wildlife supply</p>
            </div>
          </div>
          <div className='card border-wrap m30'>
            <div className='flex-3 '>
              <p className='p10'>Artwork</p>
              <p className='p10 b-top'>12022021</p>
            </div>
            <div className='flex-6 ' >
              <p className='p10'> <strong>Edit</strong></p>
              <p className='p10 b-top'>Texas wildlife supply</p>
            </div>
          </div>
          <div className='card border-wrap m30'>
            <div className='flex-3 '>
              <p className='p10'>Artwork</p>
              <p className='p10 b-top'>12022021</p>
            </div>
            <div className='flex-6 ' >
              <p className='p10'> <strong>Order</strong></p>
              <p className='p10 b-top'>IHYC frostbite burgee</p>
            </div>
          </div>
          <div className='card border-wrap m30'>
            <div className='flex-3 '>
              <p className='p10'>Artowrk</p>
              <p className='p10 b-top'>12022021</p>
            </div>
            <div className='flex-6 ' >
              <p className='p10'> <strong>Edit</strong></p>
              <p className='p10 b-top'>Texas wildlife supply</p>
            </div>
          </div>
          <div className='card border-wrap m30'>
            <div className='flex-3 '>
              <p className='p10'>Artowrk</p>
              <p className='p10 b-top'>12022021</p>
            </div>
            <div className='flex-6 ' >
              <p className='p10'> <strong>Order</strong></p>
              <p className='p10 b-top'>Texas wildlife supply</p>
            </div>
          </div>
          <div className='card border-wrap m30'>
            <div className='flex-3 '>
              <p className='p10'>Digitizing</p>
              <p className='p10 b-top'>12022021</p>
            </div>
            <div className='flex-6 ' >
              <p className='p10'> <strong>Edit</strong></p>
              <p className='p10 b-top'>IHYC frostbite burgee</p>
            </div>
          </div>
          <div className='card border-wrap m30'>
            <div className='flex-3 '>
              <p className='p10'>Artwork</p>
              <p className='p10 b-top'>12022021</p>
            </div>
            <div className='flex-6 ' >
              <p className='p10'> <strong>Quote</strong></p>
              <p className='p10 b-top'>Texas wildlife supply</p>
            </div>
          </div>
          <div className='card border-wrap m30'>
            <div className='flex-3 '>
              <p className='p10'>Artwork</p>
              <p className='p10 b-top'>12022021</p>
            </div>
            <div className='flex-6 ' >
              <p className='p10'> <strong>Quote</strong></p>
              <p className='p10 b-top'>Texas wildlife supply</p>
            </div>
          </div>
        </div>
      </div>

    </div>
  )
}
